### Login Admin
POST http://localhost:3000/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "putrodwi31",
  "password" : "putro123"
}

### Get Admin
GET http://localhost:3000/users/
Accept: application/json
Authorization: Bearer TOKEN

### Logout Admin
DELETE http://localhost:3000/users/
Accept: application/json
Authorization: Bearer TOKEN


### Get Laporan
GET http://localhost:3000/laporans/
Accept: application/json
Content-Type: application/json

### Add Laporan
POST http://localhost:3000/laporans/
Content-Type: application/json
Accept: application/json

{
  "namaPelapor": "Putro Dwi",
  "emailPelapor": "putrodwi31@gmail.com",
  "nomorPelapor": "083805200284",
  "deskripsiLaporan": "Banyak sekali sampah",
  "lokasiLaporan": "102123213.2100021, 1200012.1200321", //Longitude, Latitude
  "image": "file.png"
}

### Remove Laporan
DELETE http://localhost:3000/laporans/8
Content-Type: application/json
Accept: application/json
Authorization: Bearer TOKEN

### Update Laporan
PATCH http://localhost:3000/laporans/7
Content-Type: application/json
Accept: application/json
Authorization: Bearer TOKEN

{
  "status": 1,
  "showOnPage": 1
}

### MAIL TYPE
### 0 = SEND NOTIF TO ADMIN WHEN NEW LAPORAN
### 1 = SEND NOTIF TO PELAPOR WHEN LAPORAN IS SENDED